language: python
dist: xenial
cache: pip
python:
- 3.6
- 3.7
- 3.8-dev
- pypy3
env:
- DJANGO=1.11
- DJANGO=2.1
- DJANGO=2.2
- DJANGO=master
matrix:
  allow_failures:
  - python: 3.6
    env: DJANGO=master
  - python: 3.7
    env: DJANGO=master
  - python: 3.8-dev
    env: DJANGO=master
  - python: pypy3
    env: DJANGO=master
  fast_finish: true
install: pip install tox tox-travis codecov
after_success:
- codecov
script: tox
deploy:
  provider: pypi
  user: jazzband
  distributions: sdist bdist_wheel
  skip_existing: true
  server: https://jazzband.co/projects/django-ical/upload
  password:
    secure: EfLZobEvsD1CiqD5YqQynilokBbuRbvHkD0d7OEF2dTzQ0sahmS927k5MvDW9ILk8yY1CKnauizNycccM0A6PQvJKRYB4dkdWkkqG2er29MdnULLDjy2YEf3gcelxjSwhS43+ZG6IT/O4FoZRZVBJls03YDbKwunfe5ZtYeojYGdZx3C7m++t0Yp8V1gwjRSH1rJfLqQShte6/AYxRbnPRm+YGnkZEPUg3LCxaULWU4ewTSd+HuYjOjPYfiGkr47sHvJkw3pSP/ta2QThhSB6UqS8FP9iha7/KrkWU78opL33YVbWdEwnSgByrrWuSLiZ6uybCTaiu7CBmusQ6fQGxbV9i/oyfyI+89dH7EpMixx7OCMVEe8mcJEKqE3D4nkunMkyTzTVoNUTrowtW8NwBVLqzmkd7FmYOBa+pOHercAhyyXWYFMK+NLNAOAvrcaLIcu0vW+pCEuEqAwdPrGrQniYa5NeXTUVc8fFlRm4NuwgtniWx6aBI2xa9ItzLHBsfPPhpTr0MhTWMISKe+4K9Gtu/44/OAMvAUXBmRhV4Vw+3yF7rCQXePi+g6XcF2J9QJybHN/LE7woU3TsfUqjH0m1sjTtJfgyLbHDH0lX80mxNiNdMQJMw25n/ilhk5JSLsOOKUwqok7TvLGpWOrAVngsSSArcTtB7ffGvCQwLQ=
  on:
    tags: true
    repo: jazzband/django-ical
    python: 3.7
